-- Deprecated compatibility file.
-- The canonical non-destructive schema is maintained by:
--   php migrate.php
-- Do not execute this file separately. It represented the retired legacy webhook schema.
